export const ALGO_ACTION_TYPES = {
  SET_ALGORITHM: 'algo/SET_ALGORITHM',
  SET_IS_ALGO_DROPDOWN_OPEN: 'algo/SET_IS_ALGO_DROPDOWN_OPEN',
};

export const ALGO_TYPES = {
  BFS: 'BFS',
  DFS: 'DFS',
  ASTAR: 'A_STAR',
  DIJKSTRAS: 'DIJKSTRAS',
};
